### PR TITLE
novacustom/*_tgl: add SJF files for VBT generation

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by miczyg1** [comment]
Do we need those files here?

Secondly, without any documentation how to use those (and what has changed compared to older releases), this has very low value.

**Comment by macpijan** [comment]
@miczyg1 I think it is good idea to keep them **somewhere**, since @mkopec has used them to generate VBT, it might be useful to go back to them in the future.

I would appreciate it if you could suggest a better place if you do not like this one.

**Comment by miczyg1** [comment]
> I would appreciate it if you could suggest a better place if you do not like this one.

It was an open question, not a statement.

> Documentation has to be internal as the tool is NDA only. I thought the value here is that we can make the review of any changes publically, but no, these don't really need to be here.

I thought VBT used open tools. At least it was possible before with BSF files and BCT tool, which was publicly available on GH (not in source form, but still packages for Linux were there). So I expected to have some associated documentation how to generate/patch VBT. But I guess if the tool is NDAed, it doesn't make sense. Still it is good for tracking changes in VBT somehow.

**Comment by macpijan** [comment]
Thanks for clarification. Let's keep it there now since we have no better idea how to handle that.

**Review by macpijan — APPROVED** [review]

**Pull request merged**
