### PR TITLE
protectli/vault_jsl/V1210/descriptor.bin: Set correct bifurcation

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by mkopec** [comment]
@miczyg1 looks like the blob was signed using a different key than is linked in README

**Comment by miczyg1** [comment]
> @miczyg1 looks like the digest is signed using a different key than is linked in README
> 
> ```
> m@phaaze~/D/D/d/p/vault_jsl> wget https://raw.githubusercontent.com/3mdeb/3mdeb-secpack/refs/heads/master/dasharo/dasharo-open-source-firmware-engineering-release-signing-key.asc
> dasharo-open-source- 100% [===============================================================>]    2.94K    --.-KB/s
>                           [Files: 1  Bytes: 2.94K [18.49KB/s] Redirects: 0  Todo: 0  Errors]
> m@phaaze~/D/D/d/p/vault_jsl> gpg --import dasharo-open-source-firmware-engineering-release-signing-key.asc  main?
> gpg: key 30D70A573AAC4035: public key "Dasharo open-source firmware engineering release signing key" imported
> gpg: Total number processed: 1
> gpg:               imported: 1
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: depth: 0  valid:   2  signed:   2  trust: 0-, 0q, 0n, 0m, 0f, 2u
> gpg: depth: 1  valid:   2  signed:   0  trust: 1-, 0q, 0n, 0m, 1f, 0u
> gpg: next trustdb check due at 2025-06-27
> ```
> 
> ```
> m@phaaze~/D/D/d/p/vault_jsl> gpg -v --verify SHA256SUMS.sig SHA256SUMS                       2 v121x_bifurcation?
> gpg: enabled compatibility flags:
> gpg: Signature made Fri 22 Nov 2024 12:06:07 PM CET
> gpg:                using RSA key C55FF15BE57A9D6CE2619FF753CA1415DD4E4781
> gpg: Can't check signature: No public key
> ```

Ahh right, no more engineerting key, because releases are already public. Will change it.

**Comment by miczyg1** [comment]
Changed to the correct key in README: https://github.com/Dasharo/dasharo-blobs/compare/fc5d1fd5fabbf971d0cd9051a7f0b9300c8faf5f..0e5218dde63db6480d95f830be66dfcd37732352

**Review by mkopec — APPROVED** [review]
Thanks, all good now

**Pull request merged**
